-- The desktop bootstrap secret, self-bootstrapped on first use exactly like the credential encryption
-- key in the same row: generated by the Worker itself (32 random bytes, base64), never supplied from
-- licensing or a Worker secret. The Deploy Now flow in the desktop app (or the owner, by hand) reads it
-- out of this deployment and stores it in the desktop's secure storage; POST /v1/desktop/bootstrap then
-- requires it, in development and production alike. NULL until first requested.
ALTER TABLE mobile_sync_worker_settings ADD COLUMN desktop_bootstrap_secret_b64 TEXT;
